### PR TITLE
instruction cycle fixes

### PR DESCRIPTION
**Pull request by Seng3694**
I'm currently working on my own GB emulator. I used several sources including:
- [the unofficial GB manual][1]
- [the official GB manual][2]
- [the opcodes table][3]
- and some repos including yours

I stumbled upon some cycle errors in your cpu and thought i fix them.

[1]:http://marc.rawer.de/Gameboy/Docs/GBCPUman.pdf
[2]:https://ia801906.us.archive.org/19/items/GameBoyProgManVer1.1/GameBoyProgManVer1.1.pdf
[3]:http://www.pastraiser.com/cpu/gameboy/gameboy_opcodes.html

### CODE REVIEW

**Comment by zid** [comment]
0x19 - This is marked as 2 cycles in both docs you linked, not 3.
0x34 - This is marked as 3 in GameBoyProgMan, but 4 in gbcpuman, will have to research this one.
0x35 - Yea this is definitely wrong and should be 3/4 depending on what 0x34 is.
0xA6 - Agreed, 2.
0xAE - Agreed.
0xBE - Agreed


Conditional rets:
0xC0
0xC2 
0xC8
0xC9
0xD0
0xD8

Conditional jumps:
0xCA - Looks good.
0xD2
0xDA

16bit push:
0xD5 - Agreed, these appear to be 4.
0xC5
0xE5
0xF5 

RST:
0xC7 - I can't figure out what is totally correct here, but them all being 4 makes more sense
 than some being 3 and some being 4.
0xDF

0xD9 - Whoops, counting is hard.

I'll merge the obvious ones now, and we can do a diff to figure out what is left over.

**Comment by zid** [comment]
Okay I ended up taking absolutely every patch, there was a single patch in the wrong style but it wasn't worth the effort to break everything for it.

**Comment by Seng3694** [comment]
The gbcpuman has cycle counts which are four times larger than the ones you and the GameBoyProgMan are using. The op codes table is using these cycles too. You have to divide them by four in your system.

You can see the `INC (HL)` instruction (0x34) with 12 cycles on [page 88][1] which would be 3 cycles in your system which is also used in the official [GameBoyProgMan on page 106][2].

[1]:http://marc.rawer.de/Gameboy/Docs/GBCPUman.pdf#page=88
[2]:https://ia801906.us.archive.org/19/items/GameBoyProgManVer1.1/GameBoyProgManVer1.1.pdf#page=106

**Comment by zid** [comment]
Yes, I realize that. Those documents very definitely do not math for most
of those instructions though (which is probably why they were wrong in the
first place).

I did best 2 of 3 with those two docs and bgb/no$ and it seems all your
changes are correct.

**Pull request merged**
